TS.BAPLN.UI/TS.BAPLN.UI/Controllers/BecaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TS.BAPLN.DataEntities.DTO;
using TS.BAPLN.UI.ServiceReference;

namespace TS.BAPLN.UI.Controllers
{
    public class BecaController : Controller
    {
        // GET: Beca
        public ActionResult Index()
        {
            ServiceClient c = new ServiceClient();
            List<BecaDTO> becaL = c.ObtenerBecas().ToList();
            return View(becaL);
        }

        // GET: Beca/Create
        public ActionResult Create()
        {
            ServiceClient cliente = new ServiceClient();
            BecaDTO tb = new BecaDTO();
            tb.tipoBecas = cliente.ObtenerTipoBecas().ToList();
            return View(tb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BecaDTO becaDTO)
        {
            if (!ModelState.IsValid)
            {
                return View(becaDTO);
            }
            ServiceClient cliente = new ServiceClient();
            cliente.CrearBeca(becaDTO);
            return RedirectToAction("Index");
        }

        // GET: Beca/Edit/5
        public ActionResult Edit(int id)
        {
            ServiceClient cliente = new ServiceClient();
            BecaDTO beca = cliente.ObtenerBecaPorId(id);
            beca.tipoBecas = cliente.ObtenerTipoBecas().ToList();
            return View(beca);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BecaDTO becaDTO)
        {
            if (!ModelState.IsValid)
            {
                return View(becaDTO);
            }
            ServiceClient cliente = new ServiceClient();
            becaDTO.Id = id;
            cliente.ActualizarBeca(becaDTO);
            return RedirectToAction("Index");
        }

        public ActionResult Inactivar(int id)
        {
            ServiceClient cliente = new ServiceClient();
            cliente.InactivarBeca(id);
            return RedirectToAction("Index");
        }

        public ActionResult Activar(int id)
        {
            ServiceClient cliente = new ServiceClient();
            cliente.ActivarBeca(id);
            return RedirectToAction("Index");
        }
    }
}

TS.BAPLN.UI/TS.BAPLN.UI/Controllers/CatalogoController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using TS.BAPLN.DataEntities.DTO;
using TS.BAPLN.UI.ServiceReference;

namespace TS.BAPLN.UI.Controllers
{
    public class CatalogoController : Controller
    {
        ServiceClient cliente = null;
        CatalogosDTO catalogos = new CatalogosDTO();

        public CatalogoController()
        {
            cliente = new ServiceClient();
        }

        public ActionResult Catalogos()
        {
            ObtenerCatalogos();
            return View(catalogos);
        }

        public ActionResult Listas()
        {
            ObtenerCatalogos();
            return PartialView(catalogos);
        }

        public JsonResult Insertar(string descripcion, string catalogoId)
        {
            string result = "duplicate";
            switch (catalogoId)
            {
                case "m":
                    if (!cliente.ObtenerCatalogoMaterias().Any(m => m.Descripcion.ToLower() == descripcion.ToLower()))
                    {
                        MateriaDTO materia = new MateriaDTO();
                        materia.Descripcion = descripcion;
                        cliente.ActualizarMateria(materia);
                        result = "success";
                    }
                    break;
                case "p":
                    if (!cliente.ObtenerCatalogoPeriodos().Any(m => m.Descripcion.ToLower() == descripcion.ToLower()))
                    {
                        PeriodoDTO periodo = new PeriodoDTO();
                        periodo.Descripcion = descripcion;
                        cliente.ActualizarPeriodo(periodo);
                        result = "success";
                    }
                    break;
                case "n":
                    if (!cliente.ObtenerCatalogoNiveles().Any(m => m.Descripcion.ToLower() == descripcion.ToLower()))
                    {
                        NivelDTO nivel = new NivelDTO();
                        nivel.Descripcion = descripcion;
                        cliente.ActualizarNivel(nivel);
                        result = "success";
                    }
                    break;
                case "c":
                    if (!cliente.ObtenerCatalogoCursosLectivos().Any(m => m.Descripcion.ToLower() == descripcion.ToLower()))
                    {
                        CursoLectivoDTO cursoLectivo = new CursoLectivoDTO();
                        cursoLectivo.Descripcion = descripcion;
                        cliente.ActualizarCursoLectivo(cursoLectivo);
                        result = "success";
                    }
                    break;
            }

            return new JsonResult { Data = new { Result = result } };
        }

        public JsonResult Editar(string descripcion, string catalogoId, string itemId)
        {
            string result = "duplicate";
            switch (catalogoId)
            {
                case "m":
                    if (!cliente.ObtenerCatalogoMaterias().Any(m => m.Descripcion.ToLower() == descripcion.ToLower()))
                    {
                        MateriaDTO materia = new MateriaDTO();
                        materia.Descripcion = descripcion;
                        materia.Id = Int32.Parse(itemId);
                        cliente.ActualizarMateria(materia);
                        result = "success";
                    }
                    break;
                case "p":
                    if (!cliente.ObtenerCatalogoPeriodos().Any(m => m.Descripcion.ToLower() == descripcion.ToLower()))
                    {
                        PeriodoDTO periodo = new PeriodoDTO();
                        periodo.Descripcion = descripcion;
                        periodo.Id = Int32.Parse(itemId);
                        cliente.ActualizarPeriodo(periodo);
                        result = "success";
                    }
                    break;
                case "n":
                    if (!cliente.ObtenerCatalogoNiveles().Any(m => m.Descripcion.ToLower() == descripcion.ToLower()))
                    {
                        NivelDTO nivel = new NivelDTO();
                        nivel.Descripcion = descripcion;
                        nivel.Id = Int32.Parse(itemId);
                        cliente.ActualizarNivel(nivel);
                        result = "success";
                    }
                    break;
                case "c":
                    if (!cliente.ObtenerCatalogoCursosLectivos().Any(m => m.Descripcion.ToLower() == descripcion.ToLower()))
                    {
                        CursoLectivoDTO cursoLectivo = new CursoLectivoDTO();
                        cursoLectivo.Descripcion = descripcion;
                        cursoLectivo.Id = Int32.Parse(itemId);
                        cliente.ActualizarCursoLectivo(cursoLectivo);
                        result = "success";
                    }
                    break;
            }

            return new JsonResult { Data = new { Result = result } };
        }

        public JsonResult Activar(string catalogoId, string id)
        {
            string result = "success";

            switch (catalogoId)
            {
                case "m":                    
                        cliente.ActivarMateria(Int32.Parse(id));
                    break;
                case "p":
                    cliente.ActivarPeriodo(Int32.Parse(id));
                    break;
                case "n":
                    cliente.ActivarNivel(Int32.Parse(id));
                    break;
                case "c":
                    cliente.ActivarCursoLectivo(Int32.Parse(id));
                    break;
            }

            return new JsonResult { Data = new { Result = result } };
        }

        public JsonResult Borrar(string catalogoId, string id)
        {
            string result = "success";
            int operationResult = 1;
            switch (catalogoId)
            {
                case "m":
                    operationResult = cliente.BorrarMateria(Int32.Parse(id));
                    break;
                case "p":
                    operationResult = cliente.BorrarPeriodo(Int32.Parse(id));
                    break;
                case "n":
                    operationResult = cliente.BorrarNivel(Int32.Parse(id));
                    break;
                case "c":
                    operationResult = cliente.BorrarCursoLectivo(Int32.Parse(id));
                    break;
            }

            if (operationResult == 0)
                result = "desactivado";
            if (operationResult == 1)
                result = "borrado";

            return new JsonResult { Data = new { Result = result } };
        }

        private void ObtenerCatalogos(){
            catalogos.Materias = cliente.ObtenerCatalogoMaterias().ToList();
            catalogos.Periodos = cliente.ObtenerCatalogoPeriodos().ToList();
            catalogos.Niveles = cliente.ObtenerCatalogoNiveles().ToList();
            catalogos.CursosLectivos = cliente.ObtenerCatalogoCursosLectivos().ToList();
        }
    }
}

TS.BAPLN.UI/TS.BAPLN.UI/Controllers/DonadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TS.BAPLN.DataEntities.DTO;
using TS.BAPLN.UI.ServiceReference;

namespace TS.BAPLN.UI.Controllers
{
    public class DonadorController : Controller
    {
        public ActionResult Donadores()
        {
            ServiceClient cliente = new ServiceClient();
            List<DonadorDTO> donadores = cliente.ObtenerDonadores().ToList();
            return View(donadores);
        }

        public ActionResult Detalle(int id)
        {
            ServiceClient client = new ServiceClient();
            DonadorDTO donador = client.ObtenerDonador(id);

            return PartialView(donador);
        }

        public ActionResult Crear()
        {
            ServiceClient cliente = new ServiceClient();
            DonadorDTO donador = new DonadorDTO();
            donador.Nacionalidades = cliente.ObtenerNacionalidades().ToList();
            donador.Periodicidades = cliente.ObtenerPeriodicidades().ToList();
            return View(donador);
        }

        [HttpPost]
        public ActionResult Crear(DonadorDTO donador)
        {
            ServiceClient cliente = new ServiceClient();
            
            if (!ModelState.IsValid)
            {
                donador.Nacionalidades = cliente.ObtenerNacionalidades().ToList();
                donador.Periodicidades = cliente.ObtenerPeriodicidades().ToList();
                return View(donador);
            }
            
            cliente.CrearDonador(donador);
            return RedirectToAction("Donadores");
        }

        public ActionResult Editar(int id)
        {
            ServiceClient cliente = new ServiceClient();
            DonadorDTO donador = cliente.ObtenerDonador(id);
            donador.Nacionalidades = cliente.ObtenerNacionalidades().ToList();
            donador.Periodicidades = cliente.ObtenerPeriodicidades().ToList();
            return View(donador);
        }

        [HttpPost]
        public ActionResult Editar(int id, DonadorDTO donador)
        {
            ServiceClient cliente = new ServiceClient();

            if (!ModelState.IsValid)
            {
                donador.Nacionalidades = cliente.ObtenerNacionalidades().ToList();
                donador.Periodicidades = cliente.ObtenerPeriodicidades().ToList();
                return View(donador);
            }
            
            donador.Id = id;
            cliente.ActualizarDonador(donador);
            return RedirectToAction("Donadores");
        }

        public ActionResult Inactivar(int id)
        {
            ServiceClient cliente = new ServiceClient();
            cliente.InactivarDonador(id);
            return RedirectToAction("Donadores");
        }

        public ActionResult Activar(int id)
        {
            ServiceClient cliente = new ServiceClient();
            cliente.ActivarDonador(id);
            return RedirectToAction("Donadores");
        }
    }
}

TS.BAPLN.UI/TS.BAPLN.UI/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TS.BAPLN.DataEntities.DTO;
using TS.BAPLN.UI.ServiceReference;

namespace TS.BAPLN.UI.Controllers
{
    public class EstudianteController : Controller
    {
        public ActionResult Estudiantes()
        {
            ServiceClient cliente = new ServiceClient();
            List<EstudianteDTO> estudiantes = cliente.ObtenerEsudiantes().ToList();
            return View(estudiantes);
        }

        public ActionResult Detalle(int id)
        {
            ServiceClient client = new ServiceClient();
            EstudianteDTO estudiante = client.ObtenerEsudiante(id);

            return PartialView(estudiante);
        }

        public ActionResult Crear()
        {
            ServiceClient cliente = new ServiceClient();
            EstudianteDTO estudiante = new EstudianteDTO();
            estudiante.Nacionalidades = cliente.ObtenerNacionalidades().ToList();
            return View(estudiante);
        }

        [HttpPost]
        public ActionResult Crear(EstudianteDTO estudiante)
        {
            ServiceClient cliente = new ServiceClient();

            if (!ModelState.IsValid)
            {
                estudiante.Nacionalidades = cliente.ObtenerNacionalidades().ToList();
                return View(estudiante);
            }
            
            cliente.CrearEstudiante(estudiante);
            return RedirectToAction("Estudiantes");
        }

        public ActionResult Editar(int id)
        {
            ServiceClient cliente = new ServiceClient();
            EstudianteDTO estudiante = cliente.ObtenerEsudiante(id);
            estudiante.Nacionalidades = cliente.ObtenerNacionalidades().ToList();
            return View(estudiante);
        }

        [HttpPost]
        public ActionResult Editar(int id, EstudianteDTO estudiante)
        {
            ServiceClient cliente = new ServiceClient();
            
            if (!ModelState.IsValid)
            {
                estudiante.Nacionalidades = cliente.ObtenerNacionalidades().ToList();
                return View(estudiante);
            }
            
            estudiante.Id = id;
            cliente.ActualizarEstudiante(estudiante);
            return RedirectToAction("Estudiantes");
        }
        
        public ActionResult Inactivar(int id)
        {
            ServiceClient cliente = new ServiceClient();
            cliente.InactivarEstudiante(id);
            return RedirectToAction("Estudiantes");
        }
        
        public ActionResult Activar(int id)
        {
            ServiceClient cliente = new ServiceClient();
            cliente.ActivarEstudiante(id);
            return RedirectToAction("Estudiantes");
        }
    }
}

TS.BAPLN.UI/TS.BAPLN.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @section scripts
    {
        <script src="~/plugins/jquery-jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        <script src="~/plugins/jquery-jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <link href="~/plugins/jquery-jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" />        
    }
    <link href="~/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    <!-- ================== BEGIN BASE CSS STYLE ================== -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="~/plugins/jquery-ui/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/plugins/jquery-ui/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/animate.min.css" rel="stylesheet" />
    <link href="~/css/style.min.css" rel="stylesheet" />
    <link href="~/css/style-responsive.min.css" rel="stylesheet" />
    <link href="~/css/theme/default.css" rel="stylesheet" id="theme" />
    <!-- ================== END BASE CSS STYLE ================== -->
    <link href="~/plugins/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet" />    
    <link href="~/plugins/bootstrap-datepicker/css/datepicker.css" rel="stylesheet" />
    <link href="~/plugins/bootstrap-datepicker/css/datepicker3.css" rel="stylesheet" />
    <link href="~/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" />
    <link href="~/plugins/DataTables/media/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/plugins/DataTables/extensions/Select/css/select.bootstrap.min.css" rel="stylesheet" />
    <link href="~/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <script src="~/plugins/pace/pace.min.js"></script>

    <script src="~/plugins/jquery/jquery-1.9.1.min.js"></script>
    <script src="~/plugins/jquery/jquery-migrate-1.1.0.min.js"></script>
    <script src="~/plugins/jquery-ui/ui/minified/jquery-ui.min.js"></script>
    <script src="~/plugins/jquery-ui/ui/jquery-ui.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/plugins/jquery-cookie/jquery.cookie.js"></script>

    <script src="~/plugins/gritter/js/jquery.gritter.js"></script>
    <script src="~/plugins/flot/jquery.flot.min.js"></script>
    <script src="~/plugins/flot/jquery.flot.time.min.js"></script>
    <script src="~/plugins/flot/jquery.flot.resize.min.js"></script>
    <script src="~/plugins/flot/jquery.flot.pie.min.js"></script>
    <script src="~/plugins/sparkline/jquery.sparkline.js"></script>
    <script src="~/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/js/dashboard.min.js"></script>
    <script src="~/plugins/DataTables/media/js/jquery.dataTables.js"></script>
    <script src="~/plugins/DataTables/media/js/dataTables.bootstrap.min.js"></script>
    <script src="~/plugins/DataTables/extensions/Select/js/dataTables.select.min.js"></script>
    <script src="~/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/js/table-manage-select.demo.min.js"></script>
    <script src="~/js/apps.min.js"></script>
    <script src="~/js/Utilidades.js"></script>

    <script src="~/plugins/bootstrap3-editable/js/bootstrap-editable.js"></script>
    <script src="~/plugins/bootstrap3-editable/js/bootstrap-editable.min.js"></script>

    <title>Becas con Amor por los niños</title>
</head>
<body>
    <div id="page-container" class="page-container fade page-without-sidebar page-header-fixed page-with-top-menu">
        <div id="header" class="header navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="#" class="navbar-brand"><span class="navbar-logo"></span> Becas con Amor por los Niños.</a>
                    <button type="button" class="navbar-toggle" data-click="top-menu-toggled">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form class="navbar-form full-width">
                            <div class="form-group">

                            </div>
                        </form>
                    </li>
                    <li class="dropdown navbar-user">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="~/img/userGray.jpg" alt="" />
                            <span class="hidden-xs">Usuario Administrador</span> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu animated fadeInLeft">
                            <li class="arrow"></li>
                            <li><a href="javascript:;">Editar Perfil</a></li>
                            <li><a href="javascript:;">Cambio de Contraseña</a></li>
                            <li class="divider"></li>
                            <li><a href="javascript:;">Salir</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div id="top-menu" class="top-menu">
            <ul class="nav">
                <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret pull-right"></b>
                        <i class="fa fa-users"></i>
                        <span>Estudiantes</span> 
                    </a>
                    <ul class="sub-menu">
                        <li>@Html.ActionLink("Listado", "Estudiantes", "Estudiante")</li>
                        <li>@Html.ActionLink("Nuevo", "Crear", "Estudiante")</li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret pull-right"></b>
                        <i class="fa fa-cogs"></i>
                        <span>Donadores</span>
                    </a>
                    <ul class="sub-menu">
                        <li>@Html.ActionLink("Listado", "Donadores", "Donador")</li>
                        <li>@Html.ActionLink("Nuevo", "Crear", "Donador")</li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret pull-right"></b>
                        <i class="fa fa-book"></i>
                        <span>Becas</span>
                    </a>
                    <ul class="sub-menu">
                        <li>@Html.ActionLink("Listado", "Index", "Beca")</li>
                        <li>@Html.ActionLink("Nueva", "Create", "Beca")</li>
                        <li>@Html.ActionLink("Asignar a Estudiante", "Create", "BecaEstudiante")</li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret pull-right"></b>
                        <i class="fa fa-institution"></i>
                        <span>Instituciones</span>
                    </a>
                    <ul class="sub-menu">
                        <li>@Html.ActionLink("Listado", "Instituciones", "Institucion")</li>
                        <li>@Html.ActionLink("Nueva", "Crear", "Institucion")</li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Catalogos", "Catalogo")">
                        <i class="fa fa-list-ul"></i>
                        <span>Catálogos</span>
                    </a>
                </li>
            </ul>
        </div>
        <div id="content" class="content">
            <div class="panel-body">
                @RenderBody()
            </div>
        </div>
        <a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
        <div class="footer-fluid">
            <div class="footer-right">
                    <p>Powered by:</p>
            </div>
            <div class="footer-rightImg">
                <img src="~/img/th.png" style="height:70%" alt="" />
            </div>
        </div>
    </div>
    @*<div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@

    <!-- init page-->
    
    
    <!--[if lt IE 9]>
        <script src="assets/crossbrowserjs/html5shiv.js"></script>
        <script src="assets/crossbrowserjs/respond.min.js"></script>
        <script src="assets/crossbrowserjs/excanvas.min.js"></script>
    <![endif]-->
    <!-- ================== END BASE JS ================== -->
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            App.init();
            Dashboard.init();
            //FormPlugins.init();
            TableManageTableSelect.init();
        });
    </script>
    <style>
        .pace-activity {
            display: none !important;
            visibility: hidden !important;
        }
    </style>
</body>
</html>