TS.BAPLN.UI/TS.BAPLN.UI/Controllers/BecaEstudianteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TS.BAPLN.DataEntities.DTO;
using TS.BAPLN.UI.Models;
using TS.BAPLN.UI.ServiceReference;

namespace TS.BAPLN.UI.Controllers
{
    public class BecaEstudianteController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BecaEstudiante
        public ActionResult Index()
        {
           
            return View();
        }

        // GET: BecaEstudiante/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BecaEstudianteDTO becaEstudianteDTO = db.BecaEstudianteDTOes.Find(id);
            if (becaEstudianteDTO == null)
            {
                return HttpNotFound();
            }
            return View(becaEstudianteDTO);
        }

        // GET: BecaEstudiante/Create
        public ActionResult Create()
        {
            ServiceClient c = new ServiceClient();
            BecaEstudianteDTO b = new BecaEstudianteDTO();
            b.Becas = c.ObtenerBecasActivas().ToList();
            return View(b);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FechaInicio,FechaFinal,Id_Estudiante,Estudiante,Id_Beca,TipoBeca,Activa,MontoTotal,MontoCuota,CantidadCuotas")] BecaEstudianteDTO becaEstudianteDTO)
        {
            if (ModelState.IsValid)
            {
                db.BecaEstudianteDTOes.Add(becaEstudianteDTO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(becaEstudianteDTO);
        }

        // GET: BecaEstudiante/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BecaEstudianteDTO becaEstudianteDTO = db.BecaEstudianteDTOes.Find(id);
            if (becaEstudianteDTO == null)
            {
                return HttpNotFound();
            }
            return View(becaEstudianteDTO);
        }

        // POST: BecaEstudiante/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FechaInicio,FechaFinal,Id_Estudiante,Estudiante,Id_Beca,TipoBeca,Activa,MontoTotal,MontoCuota,CantidadCuotas")] BecaEstudianteDTO becaEstudianteDTO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(becaEstudianteDTO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(becaEstudianteDTO);
        }

        // GET: BecaEstudiante/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BecaEstudianteDTO becaEstudianteDTO = db.BecaEstudianteDTOes.Find(id);
            if (becaEstudianteDTO == null)
            {
                return HttpNotFound();
            }
            return View(becaEstudianteDTO);
        }

        // POST: BecaEstudiante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BecaEstudianteDTO becaEstudianteDTO = db.BecaEstudianteDTOes.Find(id);
            db.BecaEstudianteDTOes.Remove(becaEstudianteDTO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult ObtenerEstudiantesActivos(string prefixText)
        {
            if (prefixText.Trim().Length > 2)
            {
                List<EstudianteDTO> result = new List<EstudianteDTO>();
                ServiceClient s = new ServiceClient();

                result = s.ObtenerEstudiantesAutocomplete(prefixText).ToList();
                
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return Json("", JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TS.BAPLN.UI/TS.BAPLN.UI/Views/BecaEstudiante/Create.cshtml
@model TS.BAPLN.DataEntities.DTO.BecaEstudianteDTO

@{
    ViewBag.Title = "Create";
}

<h1 class="page-header"><small>Registro de</small> Beca a Estudiante</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">Formulario de datos</h4>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="panel-body">
                    <form class="form-horizontal">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Estudiante, htmlAttributes: new { @class = "control-label col-md-6" })

                                    @Html.EditorFor(model => model.Estudiante, new { htmlAttributes = new { @class = "form-control", @id = "txtEstudiante" } })
                                    @Html.ValidationMessageFor(model => model.Estudiante, "", new { @class = "text-danger" })

                                    @*@Html.LabelFor(model => model.Id_Estudiante, htmlAttributes: new { @class = "control-label col-md-6" })
                                    @Html.EditorFor(model => model.Id_Estudiante, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Id_Estudiante, "", new { @class = "text-danger" })*@
                                </div>
                            </div>
                            <div class ="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Id_Beca, htmlAttributes: new { @class = "control-label col-md-6" })

                                    @Html.DropDownListFor(model => model.Id_Beca, new SelectList(Model.Becas, "Id", "Descripcion"), "Seleccione una opción", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Id_Beca, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                       
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                   @Html.LabelFor(model => model.FechaInicio, htmlAttributes: new { @class = "control-label col-md-6" })
                                    @Html.EditorFor(model => model.FechaInicio, new { htmlAttributes = new { @class = "form-control", @id = "fechaInicio", @placeholder = "Seleccione", @value = "" } })
                                    @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FechaFinal, htmlAttributes: new { @class = "control-label col-md-6" })
                                    @Html.EditorFor(model => model.FechaFinal, new { htmlAttributes = new { @class = "form-control", @id = "fechaFinal", @placeholder = "Seleccione", @value = "" } })
                                    @Html.ValidationMessageFor(model => model.FechaFinal, "", new { @class = "text-danger" })
                                </div>
                                
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MontoTotal, htmlAttributes: new { @class = "control-label col-md-6" })

                                    @Html.EditorFor(model => model.MontoTotal, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MontoTotal, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.MontoCuota, htmlAttributes: new { @class = "control-label col-md-6" })

                                    @Html.EditorFor(model => model.MontoCuota, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MontoCuota, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                   
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CantidadCuotas, htmlAttributes: new { @class = "control-label col-md-6" })

                                    @Html.EditorFor(model => model.CantidadCuotas, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CantidadCuotas, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @*@Html.LabelFor(model => model.Activa, htmlAttributes: new { @class = "control-label col-md-6" })
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.Activa)
                                        @Html.ValidationMessageFor(model => model.Activa, "", new { @class = "text-danger" })
                                    </div>*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-11"></div>
                            <div class="col-md-1">
                                <button type="submit" class="btn btn-sm btn-success" value="Create">Guardar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#txtEstudiante").autocomplete({
            
            source: function (request, response) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("ObtenerEstudiantesActivos", "BecaEstudiante")",
                    dataType: "json",
                    data: { prefixText: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.Name, value: item.Name };
                        }))
                    }
                });
            },
            minLength: 3
        });
    })
        $(function () {
            $('#fechaInicio').datepicker({
                todayHighlight: true,
                autoclose: true
            });
        });

        $(function () {
            $('#fechaFinal').datepicker({
                todayHighlight: true,
                autoclose: true
            });
        });
</script>

TS.BAPLN.UI/TS.BAPLN.UI/Views/BecaEstudiante/Delete.cshtml
@model TS.BAPLN.DataEntities.DTO.BecaEstudianteDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BecaEstudianteDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id_Estudiante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Estudiante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estudiante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estudiante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id_Beca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Beca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoBeca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoBeca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoCuota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoCuota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadCuotas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadCuotas)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TS.BAPLN.UI/TS.BAPLN.UI/Views/BecaEstudiante/Details.cshtml
@model TS.BAPLN.DataEntities.DTO.BecaEstudianteDTO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BecaEstudianteDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id_Estudiante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Estudiante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estudiante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estudiante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id_Beca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Beca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoBeca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoBeca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoCuota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoCuota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadCuotas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadCuotas)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TS.BAPLN.UI/TS.BAPLN.UI/Views/BecaEstudiante/Edit.cshtml
@model TS.BAPLN.DataEntities.DTO.BecaEstudianteDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BecaEstudianteDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Estudiante, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Estudiante, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Estudiante, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estudiante, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estudiante, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estudiante, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Beca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Beca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Beca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoBeca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoBeca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoBeca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activa)
                    @Html.ValidationMessageFor(model => model.Activa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MontoTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MontoTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MontoTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MontoCuota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MontoCuota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MontoCuota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CantidadCuotas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CantidadCuotas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantidadCuotas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TS.BAPLN.UI/TS.BAPLN.UI/Views/BecaEstudiante/Index.cshtml
@model IEnumerable<TS.BAPLN.DataEntities.DTO.BecaEstudianteDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id_Estudiante)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estudiante)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id_Beca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoBeca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MontoTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MontoCuota)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CantidadCuotas)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FechaInicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaFinal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id_Estudiante)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estudiante)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id_Beca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoBeca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MontoTotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MontoCuota)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CantidadCuotas)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>